# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.

{ pkgs, lib }:

let
  vscode-utils = pkgs.vscode-utils;
in
{































































































  "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
    name = "python";
    publisher = "ms-python";
    version = "2023.21.13261010";
    sha256 = "0bhn5jqr54nvkf7hb25x2g4wigbx7rf9a2fcg6frspgd6jl8lkj8";
  };

  "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-pylance";
    publisher = "ms-python";
    version = "2023.11.13";
    sha256 = "1ayy4pp983j8fwgjffv0cy39anhl2ai1n4a4c84ngj0si18y7k0a";
  };

  "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "prettier-vscode";
    publisher = "esbenp";
    version = "10.1.0";
    sha256 = "01s0vi2h917mqfpdrhqhp2ijwkibw95yk2js0l587wvajbbry2s9";
  };

  "visualstudioexptteam"."vscodeintellicode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscodeintellicode";
    publisher = "visualstudioexptteam";
    version = "1.2.30";
    sha256 = "0lg298047vmy31fnkczgpw78k3yxzpiip0ln1wixy70hdpwsfqbz";
  };

  "ms-azuretools"."vscode-docker" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-docker";
    publisher = "ms-azuretools";
    version = "1.28.0";
    sha256 = "0nmc3pdgxpmr6k2ksdczkv9bbwszncfczik0xjympqnd2k0ra9h0";
  };

  "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gitlens";
    publisher = "eamodio";
    version = "2023.11.2404";
    sha256 = "1drw8kg34945zg6s5jrmlnwwrs60i3b1mhiqn90b8b24mb1s6xvg";
  };

  "pkief"."material-icon-theme" = vscode-utils.extensionFromVscodeMarketplace {
    name = "material-icon-theme";
    publisher = "pkief";
    version = "4.32.0";
    sha256 = "172s10fl6xs9wzwsa5shl0dp637zyar2aisv7ghd7qzqdffpz3z8";
  };

  "visualstudioexptteam"."intellicode-api-usage-examples" = vscode-utils.extensionFromVscodeMarketplace {
    name = "intellicode-api-usage-examples";
    publisher = "visualstudioexptteam";
    version = "0.2.8";
    sha256 = "1l1wjzbl5jjniyiqzlj23i3sl2xy5jsx97wsj3sbb6py0pfi4w39";
  };

  "formulahendry"."auto-rename-tag" = vscode-utils.extensionFromVscodeMarketplace {
    name = "auto-rename-tag";
    publisher = "formulahendry";
    version = "0.1.10";
    sha256 = "0nyilwfs2kbf8v3v9njx1s7ppdp1472yhimiaja0c3v7piwrcymr";
  };

  "ms-vsliveshare"."vsliveshare" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vsliveshare";
    publisher = "ms-vsliveshare";
    version = "1.0.5892";
    sha256 = "0c4xvs96ccih47l76r6l5bkjfhgiair90yy8syibdq3zshw0kxvv";
  };

  "redhat"."vscode-yaml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-yaml";
    publisher = "redhat";
    version = "1.14.0";
    sha256 = "0pww9qndd2vsizsibjsvscz9fbfx8srrj67x4vhmwr581q674944";
  };

  "christian-kohler"."path-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
    name = "path-intellisense";
    publisher = "christian-kohler";
    version = "2.8.5";
    sha256 = "1ndffv1m4ayiija1l42m28si44vx9y6x47zpxzqv2j4jj7ga1n5z";
  };

  "formulahendry"."auto-close-tag" = vscode-utils.extensionFromVscodeMarketplace {
    name = "auto-close-tag";
    publisher = "formulahendry";
    version = "0.5.14";
    sha256 = "1k4ld30fyslj89bvjh2ihwgycb0i11mn266misccbjqkci5hg1jx";
  };

  "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
    name = "go";
    publisher = "golang";
    version = "0.40.0";
    sha256 = "1k2zv49pam436cgvb970dc9n4xpdkd07lp8jllrsx5vnx7m2ml52";
  };

  "donjayamanne"."githistory" = vscode-utils.extensionFromVscodeMarketplace {
    name = "githistory";
    publisher = "donjayamanne";
    version = "0.6.20";
    sha256 = "0x9q7sh5l1frpvfss32ypxk03d73v9npnqxif4fjwcfwvx5mhiww";
  };

  "zhuangtongfa"."material-theme" = vscode-utils.extensionFromVscodeMarketplace {
    name = "material-theme";
    publisher = "zhuangtongfa";
    version = "3.16.2";
    sha256 = "0ava94zn68lxy3ph78r5rma39qz03al5l5i6x070mpa1hzj3i319";
  };

  "wholroyd"."jinja" = vscode-utils.extensionFromVscodeMarketplace {
    name = "jinja";
    publisher = "wholroyd";
    version = "0.0.8";
    sha256 = "1ln9gly5bb7nvbziilnay4q448h9npdh7sd9xy277122h0qawkci";
  };

  "yzhang"."markdown-all-in-one" = vscode-utils.extensionFromVscodeMarketplace {
    name = "markdown-all-in-one";
    publisher = "yzhang";
    version = "3.5.1";
    sha256 = "04b8hiha6z7w189lkx0lhy0sgldrfwx1yikl2463lkhhkm3f8av7";
  };

  "oderwat"."indent-rainbow" = vscode-utils.extensionFromVscodeMarketplace {
    name = "indent-rainbow";
    publisher = "oderwat";
    version = "8.3.1";
    sha256 = "0iwd6y2x2nx52hd3bsav3rrhr7dnl4n79ln09picmnh1mp4rrs3l";
  };

  "davidanson"."vscode-markdownlint" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-markdownlint";
    publisher = "davidanson";
    version = "0.52.0";
    sha256 = "0pi1vr86hmf26v6zcaaa2dhb38fcs557ihy39yrzq9rgs5qa9jk3";
  };

  "vue"."volar" = vscode-utils.extensionFromVscodeMarketplace {
    name = "volar";
    publisher = "vue";
    version = "1.8.23";
    sha256 = "12wqmc80fvsrhn7px6cpl9fcdvgm9if8sxk3qp8hxlqsr2gprs6l";
  };

  "aaron-bond"."better-comments" = vscode-utils.extensionFromVscodeMarketplace {
    name = "better-comments";
    publisher = "aaron-bond";
    version = "3.0.2";
    sha256 = "15w1ixvp6vn9ng6mmcmv9ch0ngx8m85i1yabxdfn6zx3ypq802c5";
  };

  "mikestead"."dotenv" = vscode-utils.extensionFromVscodeMarketplace {
    name = "dotenv";
    publisher = "mikestead";
    version = "1.0.1";
    sha256 = "0rs57csczwx6wrs99c442qpf6vllv2fby37f3a9rhwc8sg6849vn";
  };

  "shd101wyy"."markdown-preview-enhanced" = vscode-utils.extensionFromVscodeMarketplace {
    name = "markdown-preview-enhanced";
    publisher = "shd101wyy";
    version = "0.8.10";
    sha256 = "1qqar43h2vpynyz4gq21h5phklycw1sy2zajsn9a0hpxw7ddad06";
  };

  "bradlc"."vscode-tailwindcss" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-tailwindcss";
    publisher = "bradlc";
    version = "0.11.30";
    sha256 = "1xbcvs2i079xiah679cjczansfrgr2cp44xvydq04ndv1fyp4b6l";
  };

  "mechatroner"."rainbow-csv" = vscode-utils.extensionFromVscodeMarketplace {
    name = "rainbow-csv";
    publisher = "mechatroner";
    version = "3.8.0";
    sha256 = "0ar3s10q46fydrff8lxvg2z4m8nj3mjfi6rk3iqkl2aj4hrm36aa";
  };

  "tomoki1207"."pdf" = vscode-utils.extensionFromVscodeMarketplace {
    name = "pdf";
    publisher = "tomoki1207";
    version = "1.2.2";
    sha256 = "16rs255x569ahxldw8ra799w078h97aa2b11j97ipqgh6s5nax4b";
  };

  "gruntfuggly"."todo-tree" = vscode-utils.extensionFromVscodeMarketplace {
    name = "todo-tree";
    publisher = "gruntfuggly";
    version = "0.0.226";
    sha256 = "0yrc9qbdk7zznd823bqs1g6n2i5xrda0f9a7349kknj9wp1mqgqn";
  };

  "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-kubernetes-tools";
    publisher = "ms-kubernetes-tools";
    version = "1.3.15";
    sha256 = "1x6npc90p6b1wx5sd1hd0x0djahmffr6lw9cxh2zg10rbpq48w8i";
  };

  "ms-vscode"."makefile-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "makefile-tools";
    publisher = "ms-vscode";
    version = "0.8.16";
    sha256 = "0skxki0cfqx31cdd0a9fbxx05zxzsdipylzygihnmkdlk047qkmf";
  };

  "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform";
    publisher = "hashicorp";
    version = "2.29.2023110810";
    sha256 = "1ffz1ry1zjfmyk1v2rvjngwngvs3ppgascssq3lhad8867gviy1s";
  };

  "usernamehw"."errorlens" = vscode-utils.extensionFromVscodeMarketplace {
    name = "errorlens";
    publisher = "usernamehw";
    version = "3.15.0";
    sha256 = "0jj4mac4xqzdx0f6n9az1rh8wclbph95nnny7f4yak59yjigh3fv";
  };

  "ms-vscode"."vscode-typescript-next" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-typescript-next";
    publisher = "ms-vscode";
    version = "5.4.20231123";
    sha256 = "0gfhpza2vqfb3k21j4szj5719kn28wjjg57zkyhwhvj289jsh7w9";
  };

  "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
    name = "rust-analyzer";
    publisher = "rust-lang";
    version = "0.4.1744";
    sha256 = "0a23w8jszsiw135znl9dh1pn5vjb3mbnc5h8n77w1vmmim2cy0sb";
  };

  "quicktype"."quicktype" = vscode-utils.extensionFromVscodeMarketplace {
    name = "quicktype";
    publisher = "quicktype";
    version = "12.0.46";
    sha256 = "0mzn1favvrzqcigr74gmy167qak5saskhwcvhf7f00z7x0378dim";
  };

  "amazonwebservices"."aws-toolkit-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "aws-toolkit-vscode";
    publisher = "amazonwebservices";
    version = "1.99.0";
    sha256 = "0v8yr257yq60ccar8r4sw7m4j2g11yc21fkmrcc6m6s16fg9dd1h";
  };

  "ms-python"."black-formatter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "black-formatter";
    publisher = "ms-python";
    version = "2023.7.13171007";
    sha256 = "0kqwbv0v550icz6dvfxp19bk0yj017wyh4n6l7x27src9lkff833";
  };

  "vue"."vscode-typescript-vue-plugin" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-typescript-vue-plugin";
    publisher = "vue";
    version = "1.8.22";
    sha256 = "1094xzfzg8pjx4v1a2zbfgmcwcbyn02hkxc734nllp28w2fjrxlw";
  };

  "adpyke"."codesnap" = vscode-utils.extensionFromVscodeMarketplace {
    name = "codesnap";
    publisher = "adpyke";
    version = "1.3.4";
    sha256 = "012sj4a65sr8014z4zpxqzb6bkj7pnhm4rls73xpwawk6hwal7km";
  };

  "sibiraj-s"."vscode-scss-formatter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-scss-formatter";
    publisher = "sibiraj-s";
    version = "3.0.0";
    sha256 = "1y2przcslw4m83hq0gzndpi2ar43zpwdm3zls0fwagigpaqhr64s";
  };

  "foxundermoon"."shell-format" = vscode-utils.extensionFromVscodeMarketplace {
    name = "shell-format";
    publisher = "foxundermoon";
    version = "7.2.5";
    sha256 = "0a874423xw7z6zjj7gzzl39jahrrqcf2r16zbcvncw23483m3yli";
  };

  "gitlab"."gitlab-workflow" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gitlab-workflow";
    publisher = "gitlab";
    version = "3.86.1";
    sha256 = "1d30jv28aqkf87al9b9xm15hj36c83f00mpn0vprvfph8gbdjqfd";
  };

  "tombonnike"."vscode-status-bar-format-toggle" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-status-bar-format-toggle";
    publisher = "tombonnike";
    version = "3.2.0";
    sha256 = "0091dks9f4lxc0qgqn6zid18w8amhjx2pwkqrjq9ibwlks3cxq1j";
  };

  "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "even-better-toml";
    publisher = "tamasfe";
    version = "0.19.2";
    sha256 = "0q9z98i446cc8bw1h1mvrddn3dnpnm2gwmzwv2s3fxdni2ggma14";
  };

  "eriklynd"."json-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "json-tools";
    publisher = "eriklynd";
    version = "1.0.2";
    sha256 = "0g5ppkc0rpqaprb3l0dsdkzcgmb24apjrq88bw77qll2ra2n7l7f";
  };

  "ibm"."output-colorizer" = vscode-utils.extensionFromVscodeMarketplace {
    name = "output-colorizer";
    publisher = "ibm";
    version = "0.1.2";
    sha256 = "0i9kpnlk3naycc7k8gmcxas3s06d67wxr3nnyv5hxmsnsx5sfvb7";
  };

  "serayuzgur"."crates" = vscode-utils.extensionFromVscodeMarketplace {
    name = "crates";
    publisher = "serayuzgur";
    version = "0.6.3";
    sha256 = "1jnlakxb9zs1z8gndx5b8s01zyzind26fw387z7n09bmcyfwam5x";
  };

  "ryu1kn"."partial-diff" = vscode-utils.extensionFromVscodeMarketplace {
    name = "partial-diff";
    publisher = "ryu1kn";
    version = "1.4.3";
    sha256 = "0x3lkvna4dagr7s99yykji3x517cxk5kp7ydmqa6jb4bzzsv1s6h";
  };

  "tyriar"."sort-lines" = vscode-utils.extensionFromVscodeMarketplace {
    name = "sort-lines";
    publisher = "tyriar";
    version = "1.11.0";
    sha256 = "0c8y2b64gsfbwjy6yvzkz86vj9vqhsrf50ah0645yybc737hzzig";
  };

  "42crunch"."vscode-openapi" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-openapi";
    publisher = "42crunch";
    version = "4.18.6";
    sha256 = "1fakws7xb4cv4nmqn52352vadpanryi6g75rl3kcnizmshxxi859";
  };

  "samuelcolvin"."jinjahtml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "jinjahtml";
    publisher = "samuelcolvin";
    version = "0.20.0";
    sha256 = "14xam64dfhcq3mckw2s9bg58miw1v2jqfg1ays6ksz8b17fcn060";
  };

  "dustypomerleau"."rust-syntax" = vscode-utils.extensionFromVscodeMarketplace {
    name = "rust-syntax";
    publisher = "dustypomerleau";
    version = "0.6.1";
    sha256 = "0rccp8njr13jzsbr2jl9hqn74w7ji7b2spfd4ml6r2i43hz9gn53";
  };

  "lokalise"."i18n-ally" = vscode-utils.extensionFromVscodeMarketplace {
    name = "i18n-ally";
    publisher = "lokalise";
    version = "2.12.0";
    sha256 = "1kmfqjrwdk72wxagi36bi9ghzyyk90rfkkf3vdz5nxz0hyf708k1";
  };

  "moshfeu"."compare-folders" = vscode-utils.extensionFromVscodeMarketplace {
    name = "compare-folders";
    publisher = "moshfeu";
    version = "0.23.0";
    sha256 = "1myzx6635bz1cci1qpmays541rpj50z73cz848yffkdjigyfgqcb";
  };

  "ahmadalli"."vscode-nginx-conf" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-nginx-conf";
    publisher = "ahmadalli";
    version = "0.3.2";
    sha256 = "042wvrd1jz3wfq1v4n4zr49fzigcwba95zqxi454w9njdgzqi5d4";
  };

  "yatki"."vscode-surround" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-surround";
    publisher = "yatki";
    version = "1.5.0";
    sha256 = "1jk6z4qxbmvq8pz3nl6pfnyqnx6awby523m5k6q9g0433swpm0g0";
  };

  "charliermarsh"."ruff" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ruff";
    publisher = "charliermarsh";
    version = "2023.50.0";
    sha256 = "0dbfjzk7flyc8dnfck6pkfcms21df7y4pk2m2w0craslxz4i03q4";
  };

  "visualstudioexptteam"."vscodeintellicode-completions" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscodeintellicode-completions";
    publisher = "visualstudioexptteam";
    version = "1.0.22";
    sha256 = "1j7509qfrgmmaz6n2nhgfvsxrghid6ki5cr9clva0jbbxlxz8rpb";
  };

  "misterj"."vue-volar-extention-pack" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vue-volar-extention-pack";
    publisher = "misterj";
    version = "1.1.8";
    sha256 = "1dbc1ad260a15wvkzh3p5y503ghimcvr82mxxlg501rl11lhkmw6";
  };

  "britesnow"."vscode-toggle-quotes" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-toggle-quotes";
    publisher = "britesnow";
    version = "0.3.6";
    sha256 = "1fys7a2g7g2qdwg7r8hv728pya8a3jiq8r6vkh0g0y5qdn9wqz8y";
  };

  "wyattferguson"."jinja2-snippet-kit" = vscode-utils.extensionFromVscodeMarketplace {
    name = "jinja2-snippet-kit";
    publisher = "wyattferguson";
    version = "2.0.0";
    sha256 = "1bqq6z0iw26ypcc6azf05cy6j72j0rxz9y264x8x0infb5flkqsz";
  };

  "chouzz"."vscode-better-align" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-better-align";
    publisher = "chouzz";
    version = "1.4.2";
    sha256 = "0fb3d1j4qr90jigjxarpnnq1lx7ykzdgzlmg7zmcvia2180h6zf3";
  };

  "tim-koehler"."helm-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
    name = "helm-intellisense";
    publisher = "tim-koehler";
    version = "0.14.3";
    sha256 = "13bs7406g4nq5wfxh90zyp4yq62wlzzwl7gzkill2a56gvrfgiad";
  };

  "bibhasdn"."unique-lines" = vscode-utils.extensionFromVscodeMarketplace {
    name = "unique-lines";
    publisher = "bibhasdn";
    version = "1.0.0";
    sha256 = "1x0lkdvc0247bms200nn2z5m7qaq9lg96ppbgk6lg3mgmxknjijv";
  };

  "rubbersheep"."gi" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gi";
    publisher = "rubbersheep";
    version = "0.2.11";
    sha256 = "0j9k6wm959sziky7fh55awspzidxrrxsdbpz1d79s5lr5r19rs6j";
  };

  "ryu1kn"."text-marker" = vscode-utils.extensionFromVscodeMarketplace {
    name = "text-marker";
    publisher = "ryu1kn";
    version = "1.11.0";
    sha256 = "00xmxfd7q78y82vmw7zni524gzj79nlvvgvnx4ykd0kzhkgr4637";
  };

  "qcz"."text-power-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "text-power-tools";
    publisher = "qcz";
    version = "1.44.0";
    sha256 = "0lgk7982wxf4hlci5r7111hz8xdjkli95kgfxgyh1cd0zyccgsjw";
  };

  "takumii"."markdowntable" = vscode-utils.extensionFromVscodeMarketplace {
    name = "markdowntable";
    publisher = "takumii";
    version = "0.11.0";
    sha256 = "1fkzs9y5xnv57g84sddirsws4fvm11nsflzv688agidi2qnmlzlj";
  };

  "lunuan"."kubernetes-templates" = vscode-utils.extensionFromVscodeMarketplace {
    name = "kubernetes-templates";
    publisher = "lunuan";
    version = "1.3.1";
    sha256 = "0bjyx9ri7fl68ryy0icn1lc3r8gxkpwaxhh900ij8xfvabqvcx6m";
  };

  "hilleer"."yaml-plus-json" = vscode-utils.extensionFromVscodeMarketplace {
    name = "yaml-plus-json";
    publisher = "hilleer";
    version = "1.12.2";
    sha256 = "05ywzhmag99sxwpgid0ig3s3nv5ims9jlcxiacy8wyknxw81hikn";
  };

  "truman"."autocomplate-shell" = vscode-utils.extensionFromVscodeMarketplace {
    name = "autocomplate-shell";
    publisher = "truman";
    version = "0.1.1";
    sha256 = "0kn44m80s3w5d0870vgqlzigkf2qvg4z0ia0s2j4ql22ngrjgqak";
  };

  "monosans"."djlint" = vscode-utils.extensionFromVscodeMarketplace {
    name = "djlint";
    publisher = "monosans";
    version = "2023.11.0";
    sha256 = "0zrkd2vjlb57mdbzm7j6mbvcdysgigdk724g235kc44vm135mm49";
  };

  "nidu"."copy-json-path" = vscode-utils.extensionFromVscodeMarketplace {
    name = "copy-json-path";
    publisher = "nidu";
    version = "0.3.0";
    sha256 = "1q3mamlb8a9lzyc92091kzh2ssc6r8ffhpjsikq1aqn4lks981yf";
  };

  "gurumukhi"."selected-lines-count" = vscode-utils.extensionFromVscodeMarketplace {
    name = "selected-lines-count";
    publisher = "gurumukhi";
    version = "1.4.0";
    sha256 = "1pfnj0azhxr8gczxz4sfikq4005hra1gscs1sfl15fkqakpifw5j";
  };

  "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
    name = "nix-ide";
    publisher = "jnoortheen";
    version = "0.2.2";
    sha256 = "1264027sjh9a112si0y0p3pk3y36shj5b4qkpsj207z7lbxqq0wg";
  };

  "jq-syntax-highlighting"."jq-syntax-highlighting" = vscode-utils.extensionFromVscodeMarketplace {
    name = "jq-syntax-highlighting";
    publisher = "jq-syntax-highlighting";
    version = "0.0.2";
    sha256 = "0q91mr6a6935wnka5iga97lv78g19dlj2rz6qg3ki6w3kdlvw2h7";
  };

  "grafana"."vscode-jsonnet" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-jsonnet";
    publisher = "grafana";
    version = "0.5.1";
    sha256 = "1wdwi8ik9n3sbw908jk1jl22a69gr2ics8rc5w40ga7rgy97k059";
  };

  "reduckted"."vscode-gitweblinks" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-gitweblinks";
    publisher = "reduckted";
    version = "2.9.3";
    sha256 = "0p4v6ynhjs68albv5bqnv2z4ykdkyapycqnv0149kbdric8bbb8d";
  };

  "mgtrrz"."terraform-completer" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform-completer";
    publisher = "mgtrrz";
    version = "0.2.0";
    sha256 = "0a1kln3ylvyq2b0z0nwwmp5yqdh6l56q2x5lh7xph0h1aqcbshs3";
  };

  "noxiz"."jinja-snippets" = vscode-utils.extensionFromVscodeMarketplace {
    name = "jinja-snippets";
    publisher = "noxiz";
    version = "1.0.0";
    sha256 = "1bpb1c17pajk1drmw2rfpp3b1lls6a5pw1g7r97i1pb98xwr2qw8";
  };

  "pucelle"."run-on-save" = vscode-utils.extensionFromVscodeMarketplace {
    name = "run-on-save";
    publisher = "pucelle";
    version = "1.6.0";
    sha256 = "102w5kf4yw0fxk04x8vj0zx5w1qqxknv9j2czs7m7b6vszsv49bw";
  };

  "tfsec"."tfsec" = vscode-utils.extensionFromVscodeMarketplace {
    name = "tfsec";
    publisher = "tfsec";
    version = "1.11.0";
    sha256 = "0vvk05bw0w2krkdamrp7mw0q33giv2v0d1ikq533hk3g79qdv340";
  };

  "davidnussio"."vscode-jq-playground" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-jq-playground";
    publisher = "davidnussio";
    version = "4.3.5";
    sha256 = "15m4dblhj2v7fx5g8vd2r5qhdh7rkchgpi86szqq4yzcrc7ldflh";
  };

  "tommasov"."hosts" = vscode-utils.extensionFromVscodeMarketplace {
    name = "hosts";
    publisher = "tommasov";
    version = "1.2.0";
    sha256 = "0xc6l3ffik0kzjr8aiz8xk13fg6yfa5gyam3dyap2vwqzj3jhmgi";
  };

  "johnnymorganz"."stylua" = vscode-utils.extensionFromVscodeMarketplace {
    name = "stylua";
    publisher = "johnnymorganz";
    version = "1.5.0";
    sha256 = "0s7kglpkjwbjrxxyxwj5f28ir1i0dgd2wg76kxsh7y7b3wwg3zzs";
  };

  "thenuprojectcontributors"."vscode-nushell-lang" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-nushell-lang";
    publisher = "thenuprojectcontributors";
    version = "1.7.1";
    sha256 = "0iv1x0djyc5hsbd7f8afx4gy11dkflafjyr4lr83ghdbnvr1jn96";
  };

  "haaleo"."timing" = vscode-utils.extensionFromVscodeMarketplace {
    name = "timing";
    publisher = "haaleo";
    version = "2.7.2";
    sha256 = "13m7dxlrr7lhsam0vb0423aj5p81bgdw4idq8bl2i7rw8akpn4jg";
  };

  "mousavian"."ssh-config-syntax-highlighter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ssh-config-syntax-highlighter";
    publisher = "mousavian";
    version = "0.0.5";
    sha256 = "0z63kn3z6f73kdhz1kz206f7fib95h5mwz4i6cril9kd3q59spd2";
  };

  "maxird"."jinja-fold" = vscode-utils.extensionFromVscodeMarketplace {
    name = "jinja-fold";
    publisher = "maxird";
    version = "0.0.2";
    sha256 = "1db7hx7ixzi24nqaal0vga9gy3v6npn156rjbvhkp224a677kh7i";
  };

  "jtcontreras90"."yaml-path-extractor" = vscode-utils.extensionFromVscodeMarketplace {
    name = "yaml-path-extractor";
    publisher = "jtcontreras90";
    version = "0.0.1";
    sha256 = "1pglq52l2p2im7j0vsz3m7h34nj35bg45vjmfjyxjag7qxrcm786";
  };

  "kokakiwi"."vscode-just" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-just";
    publisher = "kokakiwi";
    version = "2.1.0";
    sha256 = "1mjj7h7d01afi3qcyflcwpi05a6n6m6ym07rz34m3mxma461cxyn";
  };

  "phil9909"."ytt-lint" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ytt-lint";
    publisher = "phil9909";
    version = "0.3.1";
    sha256 = "1b5b5rs2nhdrd58hp045hamszm4ib5zlxr2757nln81s3qkz23lr";
  };

  "yunduo"."color-highlight-css-color-4" = vscode-utils.extensionFromVscodeMarketplace {
    name = "color-highlight-css-color-4";
    publisher = "yunduo";
    version = "1.1.3";
    sha256 = "06n8v073fv7bdfg75a87f479sql12dsa95fn2wzjxhimqgpp9z6v";
  };

  "lemurdaniel"."terraform-quick-docs" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform-quick-docs";
    publisher = "lemurdaniel";
    version = "0.0.51";
    sha256 = "095mjz3iadri1a5gmhvr4wfsnggddbplx5ryr5gvharbvzg22v5z";
  };
}
