// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportedData = {
  /**
   * version
   */
  v: string;
  /**
   * engine
   */
  e: string;
  /**
   * platform
   */
  p: string;
  /**
   * hash
   */
  h: string;
  /**
   * is_prerelease
   */
  r: boolean;
};
