/*
 * Open VSX Registry API
 *
 * This API provides metadata of VS Code extensions in the Open VSX Registry as well as means to publish extensions.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Badge : A badge to be shown in the sidebar of the extension page in the registry

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Badge {
    /// Image URL of the badge
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The link users will follow when clicking the badge
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl Badge {
    /// A badge to be shown in the sidebar of the extension page in the registry
    pub fn new() -> Badge {
        Badge {
            url: None,
            href: None,
            description: None,
        }
    }
}
