/*
 * Open VSX Registry API
 *
 * This API provides metadata of VS Code extensions in the Open VSX Registry as well as means to publish extensions.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ExtensionReference : A reference to another extension in the registry

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtensionReference {
    /// URL to get metadata of the referenced extension
    #[serde(rename = "url")]
    pub url: String,
    /// Namespace of the referenced extension
    #[serde(rename = "namespace")]
    pub namespace: String,
    /// Name of the referenced extension
    #[serde(rename = "extension")]
    pub extension: String,
}

impl ExtensionReference {
    /// A reference to another extension in the registry
    pub fn new(url: String, namespace: String, extension: String) -> ExtensionReference {
        ExtensionReference {
            url,
            namespace,
            extension,
        }
    }
}
