/*
 * Open VSX Registry API
 *
 * This API provides metadata of VS Code extensions in the Open VSX Registry as well as means to publish extensions.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// NamespaceMembershipJson : List of memberships

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamespaceMembershipJson {
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::User>>,
}

impl NamespaceMembershipJson {
    /// List of memberships
    pub fn new() -> NamespaceMembershipJson {
        NamespaceMembershipJson {
            namespace: None,
            role: None,
            user: None,
        }
    }
}
