/*
 * Open VSX Registry API
 *
 * This API provides metadata of VS Code extensions in the Open VSX Registry as well as means to publish extensions.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// NamespaceMembershipList : Metadata of a namespace member list

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamespaceMembershipList {
    /// Indicates success of the operation (omitted if a more specific result type is returned)
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<String>,
    /// Indicates a warning; when this is present, other properties can still be used
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
    /// Indicates an error; when this is present, all other properties should be ignored
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// List of memberships
    #[serde(rename = "namespaceMemberships")]
    pub namespace_memberships: Vec<crate::models::NamespaceMembershipJson>,
}

impl NamespaceMembershipList {
    /// Metadata of a namespace member list
    pub fn new(
        namespace_memberships: Vec<crate::models::NamespaceMembershipJson>,
    ) -> NamespaceMembershipList {
        NamespaceMembershipList {
            success: None,
            warning: None,
            error: None,
            namespace_memberships,
        }
    }
}
