/*
 * Open VSX Registry API
 *
 * This API provides metadata of VS Code extensions in the Open VSX Registry as well as means to publish extensions.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReviewList : List of reviews of an extension

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewList {
    /// Indicates success of the operation (omitted if a more specific result type is returned)
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<String>,
    /// Indicates a warning; when this is present, other properties can still be used
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
    /// Indicates an error; when this is present, all other properties should be ignored
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "reviews")]
    pub reviews: Vec<crate::models::Review>,
}

impl ReviewList {
    /// List of reviews of an extension
    pub fn new(reviews: Vec<crate::models::Review>) -> ReviewList {
        ReviewList {
            success: None,
            warning: None,
            error: None,
            reviews,
        }
    }
}
