/*
 * Open VSX Registry API
 *
 * This API provides metadata of VS Code extensions in the Open VSX Registry as well as means to publish extensions.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Review : A review of an extension

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Review {
    #[serde(rename = "user")]
    pub user: Box<crate::models::User>,
    /// Date and time when this review was posted (ISO-8601)
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Number of stars
    #[serde(rename = "rating")]
    pub rating: i32,
}

impl Review {
    /// A review of an extension
    pub fn new(user: crate::models::User, timestamp: String, rating: i32) -> Review {
        Review {
            user: Box::new(user),
            timestamp,
            comment: None,
            rating,
        }
    }
}
