/*
 * Open VSX Registry API
 *
 * This API provides metadata of VS Code extensions in the Open VSX Registry as well as means to publish extensions.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Versions : Map of versions matching an extension

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Versions {
    /// Indicates success of the operation (omitted if a more specific result type is returned)
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<String>,
    /// Indicates a warning; when this is present, other properties can still be used
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
    /// Indicates an error; when this is present, all other properties should be ignored
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Number of skipped entries according to the versions request
    #[serde(rename = "offset")]
    pub offset: i32,
    /// Total number of versions the extension has
    #[serde(rename = "totalSize")]
    pub total_size: i32,
    /// Map of versions, limited to the size specified in the versions request
    #[serde(rename = "versions")]
    pub versions: ::std::collections::HashMap<String, String>,
}

impl Versions {
    /// Map of versions matching an extension
    pub fn new(
        offset: i32,
        total_size: i32,
        versions: ::std::collections::HashMap<String, String>,
    ) -> Versions {
        Versions {
            success: None,
            warning: None,
            error: None,
            offset,
            total_size,
            versions,
        }
    }
}
