name: "gate"

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Install taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz \ | gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Check style
        env:
           RUST_LOG: DEBUG
        run: |
          pip install pre-commit
          cargo clippy -- -Dwarnings
          cargo test

      - name: Check nix
        run: |
          cargo run -- config.toml -o example/vscode_plugins.nix
          cat example/vscode_plugins.nix
          cd example && nix develop --build
